services:
  - type: web
    name: pricehunt-scraper
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: python app.py
    plan: free
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /tmp/playwright