services:
  - type: web
    name: pricehunt-scraper
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install --with-deps
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    plan: free
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.cache/playwright